name: flask on aws

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python test_main.py
        continue-on-error: true

      - name: Start Flask App and Capture Output
        run: |
          nohup python3 main.py > index.html 2>&1 &

      - name: Wait for Flask app to start
        run: sleep 20  # Adjust the sleep time as needed

      - name: Configure AWS Credentials
        if: ${{ success() }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy static site to S3 bucket
        if: ${{ success() }}
        run: aws s3 sync . s3://tws-portfolio --delete
